// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudentApi;

namespace StudentApi.Migrations
{
    [DbContext(typeof(SQLiteDBContext))]
    partial class SQLiteDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3");

            modelBuilder.Entity("StudentApi.Students", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Career")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 24,
                            Career = "Systems engineer",
                            FirstName = "Juan",
                            LastName = "Montoya",
                            Username = "juan.montoya"
                        },
                        new
                        {
                            Id = 2,
                            Age = 23,
                            Career = "Systems engineer",
                            FirstName = "Juan",
                            LastName = "Moreno",
                            Username = "juan.moreno"
                        },
                        new
                        {
                            Id = 3,
                            Age = 19,
                            Career = "Public Health Administration",
                            FirstName = "Sara",
                            LastName = "Cardona",
                            Username = "sara.carmona"
                        },
                        new
                        {
                            Id = 4,
                            Age = 22,
                            Career = "Public Health Administration",
                            FirstName = "Stasy",
                            LastName = "Castro",
                            Username = "stasy.castro"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
